FROM php:5.6.23-fpm

RUN apt-get update && apt-get install -y zlib1g-dev libcurl4-gnutls-dev libpng-dev libxml2-dev libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached

RUN docker-php-ext-install pdo pdo_mysql curl iconv gd mbstring xml xmlreader xmlwriter mysqli